import { DEMO_ROLE_IDS, type RoleId } from "../packages/domain/src/index.js";
import { PERMISSIONS, type Permission } from "../packages/security/src/index.js";

/**
 * Immutable pre-Phase-3.0 approved grants. This is a literal fixture, not an alias of
 * `ROLE_PERMISSION_MATRIX`. It includes previously approved Phase 2.0 lead and Phase 2.3
 * Digital Workforce grants that were already frozen on `main`.
 */
export const APPROVED_PHASE1_ROLE_PERMISSIONS: Readonly<Record<RoleId, readonly Permission[]>> = {
  [DEMO_ROLE_IDS.OWNER_ADMIN]: Object.values(PERMISSIONS),
  [DEMO_ROLE_IDS.SALES]: [
    PERMISSIONS.HOME_VIEW,
    PERMISSIONS.COMPANIES_VIEW,
    PERMISSIONS.COMPANIES_MANAGE,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.LEADS_VIEW,
    PERMISSIONS.LEADS_MANAGE,
    PERMISSIONS.LEADS_REVIEW,
    PERMISSIONS.LEADS_DISQUALIFY,
    PERMISSIONS.PROPOSALS_VIEW,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_MANAGE,
    PERMISSIONS.ACTIVITIES_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_MANAGE,
    PERMISSIONS.SEARCH_VIEW,
    PERMISSIONS.AI_COMMAND_VIEW,
    PERMISSIONS.AI_COMMAND_RUN,
    PERMISSIONS.TASK_ACTION_EXECUTE,
    PERMISSIONS.COMMUNICATIONS_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.DIGITAL_WORKFORCE_VIEW,
    PERMISSIONS.DIGITAL_WORKFORCE_RUN,
  ],
  [DEMO_ROLE_IDS.OPERATIONS]: [
    PERMISSIONS.HOME_VIEW,
    PERMISSIONS.COMPANIES_VIEW,
    PERMISSIONS.COMPANIES_MANAGE,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.PROJECTS_VIEW,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_MANAGE,
    PERMISSIONS.ACTIVITIES_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.NOTIFICATIONS_MANAGE,
    PERMISSIONS.SEARCH_VIEW,
    PERMISSIONS.AI_COMMAND_VIEW,
    PERMISSIONS.AI_COMMAND_RUN,
    PERMISSIONS.TASK_ACTION_EXECUTE,
    PERMISSIONS.WORKFLOW_VIEW,
    PERMISSIONS.COMMUNICATIONS_VIEW,
    PERMISSIONS.DOCUMENTS_VIEW,
    PERMISSIONS.AUTOMATIONS_VIEW,
    PERMISSIONS.FOUNDATION_WORKFLOW_RUN,
    PERMISSIONS.DIGITAL_WORKFORCE_VIEW,
    PERMISSIONS.DIGITAL_WORKFORCE_RUN,
  ],
  [DEMO_ROLE_IDS.EXECUTIVE_READONLY]: [
    PERMISSIONS.HOME_VIEW,
    PERMISSIONS.COMPANIES_VIEW,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.TASKS_VIEW,
    PERMISSIONS.TASKS_VIEW_ALL,
    PERMISSIONS.ACTIVITIES_VIEW,
    PERMISSIONS.NOTIFICATIONS_VIEW,
    PERMISSIONS.SEARCH_VIEW,
    PERMISSIONS.AI_COMMAND_VIEW,
    PERMISSIONS.AI_COMMAND_RUN,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.DIGITAL_WORKFORCE_VIEW,
    PERMISSIONS.DIGITAL_WORKFORCE_RUN,
  ],
  [DEMO_ROLE_IDS.INTEGRATION_ADMIN]: [
    PERMISSIONS.HOME_VIEW,
    PERMISSIONS.SEARCH_VIEW,
    PERMISSIONS.AI_COMMAND_VIEW,
    PERMISSIONS.AI_COMMAND_RUN,
    PERMISSIONS.AI_INTEGRATION_HEALTH_VIEW,
    PERMISSIONS.INTEGRATIONS_VIEW,
    PERMISSIONS.INTEGRATIONS_MANAGE,
    PERMISSIONS.ADMINISTRATION_VIEW,
    PERMISSIONS.SETTINGS_MANAGE,
  ],
};

/**
 * Approved Phase 3.0 inspection-to-report permission deltas. Owner-admin continues to receive
 * every current permission. `reports.deliver` remains Owner-only.
 */
export const APPROVED_PHASE3_ROLE_PERMISSION_DELTAS: Readonly<
  Record<RoleId, readonly Permission[]>
> = {
  [DEMO_ROLE_IDS.OWNER_ADMIN]: [],
  [DEMO_ROLE_IDS.SALES]: [
    PERMISSIONS.OPERATIONS_BOARD_VIEW,
    PERMISSIONS.INSPECTIONS_VIEW,
    PERMISSIONS.REPORTS_VIEW,
  ],
  [DEMO_ROLE_IDS.OPERATIONS]: [
    PERMISSIONS.PROJECTS_MANAGE,
    PERMISSIONS.AUTOMATIONS_OPERATE,
    PERMISSIONS.OPERATIONS_BOARD_VIEW,
    PERMISSIONS.INSPECTIONS_VIEW,
    PERMISSIONS.INSPECTIONS_SUBMIT,
    PERMISSIONS.INSPECTIONS_CORRECT,
    PERMISSIONS.REPORTS_VIEW,
    PERMISSIONS.REPORTS_REVIEW,
    PERMISSIONS.REPORTS_APPROVE,
    PERMISSIONS.EXCEPTIONS_VIEW,
    PERMISSIONS.EXCEPTIONS_MANAGE,
  ],
  [DEMO_ROLE_IDS.EXECUTIVE_READONLY]: [
    PERMISSIONS.OPERATIONS_BOARD_VIEW,
    PERMISSIONS.INSPECTIONS_VIEW,
    PERMISSIONS.EXCEPTIONS_VIEW,
  ],
  [DEMO_ROLE_IDS.INTEGRATION_ADMIN]: [],
};

export const APPROVED_PHASE31A_ROLE_PERMISSION_DELTAS: Readonly<
  Record<RoleId, readonly Permission[]>
> = {
  [DEMO_ROLE_IDS.OWNER_ADMIN]: [],
  [DEMO_ROLE_IDS.SALES]: [],
  [DEMO_ROLE_IDS.OPERATIONS]: [PERMISSIONS.CONFIGURATION_VIEW, PERMISSIONS.CONFIGURATION_DRY_RUN],
  [DEMO_ROLE_IDS.EXECUTIVE_READONLY]: [PERMISSIONS.CONFIGURATION_VIEW],
  [DEMO_ROLE_IDS.INTEGRATION_ADMIN]: [
    PERMISSIONS.CONFIGURATION_VIEW,
    PERMISSIONS.CONFIGURATION_DRAFT,
    PERMISSIONS.CONFIGURATION_VALIDATE,
    PERMISSIONS.CONFIGURATION_MAPPING_EDIT,
    PERMISSIONS.CONFIGURATION_DRY_RUN,
  ],
};

export const APPROVED_PHASE32A_ROLE_PERMISSION_DELTAS: Readonly<
  Record<RoleId, readonly Permission[]>
> = {
  [DEMO_ROLE_IDS.OWNER_ADMIN]: [],
  [DEMO_ROLE_IDS.SALES]: [],
  [DEMO_ROLE_IDS.OPERATIONS]: [
    PERMISSIONS.WORK_VIEW,
    PERMISSIONS.WORK_CLAIM,
    PERMISSIONS.WORK_UPDATE,
    PERMISSIONS.WORK_NOTIFICATIONS_VIEW,
  ],
  [DEMO_ROLE_IDS.EXECUTIVE_READONLY]: [
    PERMISSIONS.WORK_VIEW,
    PERMISSIONS.WORK_NOTIFICATIONS_VIEW,
    PERMISSIONS.WORK_SCHEDULES_VIEW,
  ],
  [DEMO_ROLE_IDS.INTEGRATION_ADMIN]: [
    PERMISSIONS.WORK_VIEW,
    PERMISSIONS.WORK_CLAIM,
    PERMISSIONS.WORK_UPDATE,
    PERMISSIONS.WORK_NOTIFICATIONS_VIEW,
    PERMISSIONS.WORK_SCHEDULES_VIEW,
    PERMISSIONS.WORK_SCHEDULES_MANAGE,
  ],
};

export const APPROVED_PHASE33A_ROLE_PERMISSION_DELTAS: Readonly<
  Record<RoleId, readonly Permission[]>
> = {
  [DEMO_ROLE_IDS.OWNER_ADMIN]: [],
  [DEMO_ROLE_IDS.SALES]: [
    PERMISSIONS.PROPOSALS_CREATE,
    PERMISSIONS.PROPOSALS_EDIT,
    PERMISSIONS.PROPOSALS_SUBMIT,
    PERMISSIONS.PROPOSALS_OVERRIDE_REQUEST,
    PERMISSIONS.PROPOSALS_DELIVERY_PLAN,
    PERMISSIONS.PROPOSALS_WORK_VIEW,
    PERMISSIONS.PROPOSALS_WORK_CLAIM,
  ],
  [DEMO_ROLE_IDS.OPERATIONS]: [PERMISSIONS.PROPOSALS_VIEW],
  [DEMO_ROLE_IDS.EXECUTIVE_READONLY]: [PERMISSIONS.PROPOSALS_VIEW],
  [DEMO_ROLE_IDS.INTEGRATION_ADMIN]: [
    PERMISSIONS.PROPOSALS_VIEW,
    PERMISSIONS.SERVICE_CATALOG_VIEW,
    PERMISSIONS.SERVICE_CATALOG_MANAGE,
    PERMISSIONS.COMMERCIAL_POLICY_VIEW,
    PERMISSIONS.COMMERCIAL_POLICY_MANAGE,
  ],
};

export const APPROVED_CURRENT_ROLE_PERMISSIONS: Readonly<Record<RoleId, readonly Permission[]>> =
  Object.fromEntries(
    Object.values(DEMO_ROLE_IDS).map((roleId) => [
      roleId,
      roleId === DEMO_ROLE_IDS.OWNER_ADMIN
        ? Object.values(PERMISSIONS)
        : [
            ...APPROVED_PHASE1_ROLE_PERMISSIONS[roleId],
            ...APPROVED_PHASE3_ROLE_PERMISSION_DELTAS[roleId],
            ...APPROVED_PHASE31A_ROLE_PERMISSION_DELTAS[roleId],
            ...APPROVED_PHASE32A_ROLE_PERMISSION_DELTAS[roleId],
            ...APPROVED_PHASE33A_ROLE_PERMISSION_DELTAS[roleId],
          ],
    ]),
  ) as Readonly<Record<RoleId, readonly Permission[]>>;
