import type { JsonObject } from "./entities.js";
import {
  BEA_PRODUCTION_POLICY_UNCONFIGURED,
  CONFIGURATION_SYNTHETIC_DISCLOSURE,
  defaultReviewPolicy,
  type BoundConfigurationPackage,
  type CollectionItemBinding,
  type ConfigurationIntakeItem,
  type ConfigurationReadinessItem,
  type DeliveryPolicyDefinition,
  type InspectionSchemaDefinition,
  type MappingTransform,
  type ReportTemplateDefinition,
  type SlaPolicyDefinition,
  type SourceCollectionMapping,
  type SourceMappingProfile,
  type StoragePolicyDefinition,
  type ValidationRuleSet,
  type WorkflowBlueprintParameters,
} from "./configuration.js";
import {
  COMMERCIAL_INTAKE_QUESTIONS,
  COMMERCIAL_INTAKE_SECTIONS,
  COMMERCIAL_READINESS_GAPS,
} from "./synthetic-catalogs.js";

const DISCLOSURE = CONFIGURATION_SYNTHETIC_DISCLOSURE;

const PHOTO_SHA = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa";
const SIGNATURE_SHA = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb";
const MOISTURE_PHOTO_SHA = "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc";
const ALT_PHOTO_ONE = "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd";
const ALT_PHOTO_TWO = "eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee";

function itemBind(
  destination: string,
  sourcePath: string,
  required = false,
  transforms: readonly MappingTransform[] = [],
): CollectionItemBinding {
  return { destination, sourcePath, transforms, required };
}

function collection(
  input: Omit<SourceCollectionMapping, "itemBindings"> & {
    readonly itemBindings: readonly CollectionItemBinding[];
  },
): SourceCollectionMapping {
  return input;
}

function schema(
  key: string,
  displayName: string,
  extraFields: InspectionSchemaDefinition["fields"],
  extraSections: InspectionSchemaDefinition["sections"] = [],
): InspectionSchemaDefinition {
  return {
    schemaKey: key,
    schemaVersion: 1,
    displayName,
    synthetic: true,
    disclosure: DISCLOSURE,
    sections: [
      {
        key: "site",
        label: "Site and client",
        description: "Who and where the inspection covers.",
        displayOrder: 1,
        parentKey: null,
        repeatable: false,
      },
      {
        key: "fieldwork",
        label: "Fieldwork",
        description: "Inspector identity and completion time.",
        displayOrder: 2,
        parentKey: null,
        repeatable: false,
      },
      {
        key: "findings",
        label: "Findings",
        description: "Observed conditions.",
        displayOrder: 3,
        parentKey: null,
        repeatable: true,
      },
      ...extraSections,
    ],
    fields: [
      {
        key: "client_name",
        label: "Client name",
        description: "Client organization name.",
        dataType: "string",
        required: true,
        defaultStatus: "required",
        sectionKey: "site",
        displayOrder: 1,
        repeatableGroup: null,
        allowedValues: null,
        unit: null,
        minimum: null,
        maximum: null,
        minLength: 1,
        maxLength: 200,
        dateRule: null,
        privacyClassification: "operational",
        evidenceRelationship: "none",
        findingRelationship: "none",
        sourceLineageRequired: true,
        correctionGuidance: "Enter the client organization name.",
        visibleIf: null,
        requiredIf: null,
      },
      {
        key: "site_name",
        label: "Site name",
        description: "Inspected site.",
        dataType: "string",
        required: true,
        defaultStatus: "required",
        sectionKey: "site",
        displayOrder: 2,
        repeatableGroup: null,
        allowedValues: null,
        unit: null,
        minimum: null,
        maximum: null,
        minLength: 1,
        maxLength: 200,
        dateRule: null,
        privacyClassification: "operational",
        evidenceRelationship: "none",
        findingRelationship: "none",
        sourceLineageRequired: true,
        correctionGuidance: "Enter the site name.",
        visibleIf: null,
        requiredIf: null,
      },
      {
        key: "inspector_name",
        label: "Inspector name",
        description: "Person who performed the inspection.",
        dataType: "person_contact",
        required: true,
        defaultStatus: "required",
        sectionKey: "fieldwork",
        displayOrder: 3,
        repeatableGroup: null,
        allowedValues: null,
        unit: null,
        minimum: null,
        maximum: null,
        minLength: 1,
        maxLength: 200,
        dateRule: null,
        privacyClassification: "restricted",
        evidenceRelationship: "none",
        findingRelationship: "none",
        sourceLineageRequired: true,
        correctionGuidance: "Enter the inspector's name.",
        visibleIf: null,
        requiredIf: null,
      },
      {
        key: "completed_at",
        label: "Completed at",
        description: "Inspection completion timestamp.",
        dataType: "timestamp",
        required: true,
        defaultStatus: "required",
        sectionKey: "fieldwork",
        displayOrder: 4,
        repeatableGroup: null,
        allowedValues: null,
        unit: null,
        minimum: null,
        maximum: null,
        minLength: null,
        maxLength: null,
        dateRule: "iso-8601",
        privacyClassification: "operational",
        evidenceRelationship: "none",
        findingRelationship: "none",
        sourceLineageRequired: true,
        correctionGuidance: "Enter the completion timestamp.",
        visibleIf: null,
        requiredIf: null,
      },
      {
        key: "attestation",
        label: "Inspector attestation",
        description: "Inspector attests the package is complete.",
        dataType: "boolean",
        required: true,
        defaultStatus: "required",
        sectionKey: "fieldwork",
        displayOrder: 5,
        repeatableGroup: null,
        allowedValues: ["true", "false"],
        unit: null,
        minimum: null,
        maximum: null,
        minLength: null,
        maxLength: null,
        dateRule: null,
        privacyClassification: "signature",
        evidenceRelationship: "none",
        findingRelationship: "none",
        sourceLineageRequired: true,
        correctionGuidance: "Confirm attestation before submission.",
        visibleIf: null,
        requiredIf: null,
      },
      {
        key: "summary",
        label: "Narrative summary",
        description: "Optional narrative. Not BEA production wording.",
        dataType: "multiline_text",
        required: false,
        defaultStatus: "optional",
        sectionKey: "findings",
        displayOrder: 90,
        repeatableGroup: null,
        allowedValues: null,
        unit: null,
        minimum: null,
        maximum: null,
        minLength: null,
        maxLength: 4000,
        dateRule: null,
        privacyClassification: "operational",
        evidenceRelationship: "none",
        findingRelationship: "none",
        sourceLineageRequired: false,
        correctionGuidance: "A summary is useful but not required by this synthetic rule set.",
        visibleIf: null,
        requiredIf: null,
      },
      ...extraFields,
    ],
  };
}

const exteriorSchema = schema(
  "synthetic-exterior-observation",
  "Synthetic Exterior Observation schema",
  [
    {
      key: "weather",
      label: "Weather",
      description: "Observed weather. Synthetic demonstration field only.",
      dataType: "enum",
      required: true,
      defaultStatus: "required",
      sectionKey: "fieldwork",
      displayOrder: 6,
      repeatableGroup: null,
      allowedValues: ["clear", "overcast", "rain", "snow"],
      unit: null,
      minimum: null,
      maximum: null,
      minLength: null,
      maxLength: null,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "none",
      findingRelationship: "none",
      sourceLineageRequired: true,
      correctionGuidance: "Select the observed weather condition.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "elevation",
      label: "Elevation",
      description: "Primary elevation observed.",
      dataType: "enum",
      required: true,
      defaultStatus: "required",
      sectionKey: "fieldwork",
      displayOrder: 7,
      repeatableGroup: null,
      allowedValues: ["north", "south", "east", "west"],
      unit: null,
      minimum: null,
      maximum: null,
      minLength: null,
      maxLength: null,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "none",
      findingRelationship: "none",
      sourceLineageRequired: true,
      correctionGuidance: "Select the elevation.",
      visibleIf: null,
      requiredIf: null,
    },
  ],
  [
    {
      key: "photos",
      label: "Photo grid",
      description: "Captioned photos for the exterior observation.",
      displayOrder: 4,
      parentKey: null,
      repeatable: true,
    },
  ],
);

const moistureSchema = schema(
  "synthetic-moisture-investigation",
  "Synthetic Moisture Investigation schema",
  [
    {
      key: "indoor_rh",
      label: "Indoor relative humidity",
      description: "Indoor RH percent. Synthetic demonstration field only.",
      dataType: "decimal",
      required: true,
      defaultStatus: "required",
      sectionKey: "fieldwork",
      displayOrder: 6,
      repeatableGroup: null,
      allowedValues: null,
      unit: "%RH",
      minimum: 0,
      maximum: 100,
      minLength: null,
      maxLength: null,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "none",
      findingRelationship: "none",
      sourceLineageRequired: true,
      correctionGuidance: "Enter indoor relative humidity.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "outdoor_rh",
      label: "Outdoor relative humidity",
      description: "Outdoor RH percent.",
      dataType: "decimal",
      required: true,
      defaultStatus: "required",
      sectionKey: "fieldwork",
      displayOrder: 7,
      repeatableGroup: null,
      allowedValues: null,
      unit: "%RH",
      minimum: 0,
      maximum: 100,
      minLength: null,
      maxLength: null,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "none",
      findingRelationship: "none",
      sourceLineageRequired: true,
      correctionGuidance: "Enter outdoor relative humidity.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "finding_code",
      label: "Finding code",
      description: "CSV finding code retained as a scalar lineage field.",
      dataType: "string",
      required: false,
      defaultStatus: "optional",
      sectionKey: "findings",
      displayOrder: 20,
      repeatableGroup: null,
      allowedValues: null,
      unit: null,
      minimum: null,
      maximum: null,
      minLength: null,
      maxLength: 80,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "none",
      findingRelationship: "is_finding",
      sourceLineageRequired: false,
      correctionGuidance: "Supply a finding code.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "finding_title",
      label: "Finding title",
      description: "CSV finding title retained as a scalar lineage field.",
      dataType: "string",
      required: false,
      defaultStatus: "optional",
      sectionKey: "findings",
      displayOrder: 21,
      repeatableGroup: null,
      allowedValues: null,
      unit: null,
      minimum: null,
      maximum: null,
      minLength: 1,
      maxLength: 200,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "none",
      findingRelationship: "is_finding",
      sourceLineageRequired: false,
      correctionGuidance: "Supply a finding title.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "finding_description",
      label: "Finding description",
      description: "CSV finding description retained as a scalar lineage field.",
      dataType: "multiline_text",
      required: false,
      defaultStatus: "optional",
      sectionKey: "findings",
      displayOrder: 22,
      repeatableGroup: null,
      allowedValues: null,
      unit: null,
      minimum: null,
      maximum: null,
      minLength: null,
      maxLength: 4000,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "none",
      findingRelationship: "none",
      sourceLineageRequired: false,
      correctionGuidance: "Describe the finding.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "photo_filename",
      label: "Photo filename",
      description: "CSV photo filename retained as a scalar lineage field.",
      dataType: "string",
      required: false,
      defaultStatus: "optional",
      sectionKey: "findings",
      displayOrder: 23,
      repeatableGroup: null,
      allowedValues: null,
      unit: null,
      minimum: null,
      maximum: null,
      minLength: null,
      maxLength: 200,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "is_evidence",
      findingRelationship: "none",
      sourceLineageRequired: false,
      correctionGuidance: "Supply a photo filename.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "photo_sha256",
      label: "Photo SHA-256",
      description: "CSV photo digest retained as a scalar lineage field.",
      dataType: "string",
      required: false,
      defaultStatus: "optional",
      sectionKey: "findings",
      displayOrder: 24,
      repeatableGroup: null,
      allowedValues: null,
      unit: null,
      minimum: null,
      maximum: null,
      minLength: 64,
      maxLength: 64,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "is_evidence",
      findingRelationship: "none",
      sourceLineageRequired: false,
      correctionGuidance: "Supply a SHA-256 digest.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "photo_caption",
      label: "Photo caption",
      description: "CSV photo caption retained as a scalar lineage field.",
      dataType: "string",
      required: false,
      defaultStatus: "optional",
      sectionKey: "findings",
      displayOrder: 25,
      repeatableGroup: null,
      allowedValues: null,
      unit: null,
      minimum: null,
      maximum: null,
      minLength: null,
      maxLength: 400,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "none",
      findingRelationship: "none",
      sourceLineageRequired: false,
      correctionGuidance: "Caption the photo.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "signature_sha256",
      label: "Signature SHA-256",
      description: "CSV signature digest retained as a scalar lineage field.",
      dataType: "string",
      required: false,
      defaultStatus: "optional",
      sectionKey: "fieldwork",
      displayOrder: 26,
      repeatableGroup: null,
      allowedValues: null,
      unit: null,
      minimum: null,
      maximum: null,
      minLength: 64,
      maxLength: 64,
      dateRule: null,
      privacyClassification: "signature",
      evidenceRelationship: "is_evidence",
      findingRelationship: "none",
      sourceLineageRequired: false,
      correctionGuidance: "Supply a signature digest.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "reading1_location",
      label: "Reading 1 location",
      description: "CSV first meter location retained as a scalar lineage field.",
      dataType: "string",
      required: false,
      defaultStatus: "optional",
      sectionKey: "moisture_readings",
      displayOrder: 27,
      repeatableGroup: "moisture_readings",
      allowedValues: null,
      unit: null,
      minimum: null,
      maximum: null,
      minLength: null,
      maxLength: 200,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "none",
      findingRelationship: "none",
      sourceLineageRequired: false,
      correctionGuidance: "Supply the first reading location.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "reading1_pct",
      label: "Reading 1 percent",
      description: "CSV first meter value retained as a scalar lineage field.",
      dataType: "decimal",
      required: false,
      defaultStatus: "optional",
      sectionKey: "moisture_readings",
      displayOrder: 28,
      repeatableGroup: "moisture_readings",
      allowedValues: null,
      unit: "%",
      minimum: 0,
      maximum: 100,
      minLength: null,
      maxLength: null,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "none",
      findingRelationship: "none",
      sourceLineageRequired: false,
      correctionGuidance: "Supply the first reading.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "reading2_location",
      label: "Reading 2 location",
      description: "CSV second meter location retained as a scalar lineage field.",
      dataType: "string",
      required: false,
      defaultStatus: "optional",
      sectionKey: "moisture_readings",
      displayOrder: 29,
      repeatableGroup: "moisture_readings",
      allowedValues: null,
      unit: null,
      minimum: null,
      maximum: null,
      minLength: null,
      maxLength: 200,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "none",
      findingRelationship: "none",
      sourceLineageRequired: false,
      correctionGuidance: "Supply the second reading location.",
      visibleIf: null,
      requiredIf: null,
    },
    {
      key: "reading2_pct",
      label: "Reading 2 percent",
      description: "CSV second meter value retained as a scalar lineage field.",
      dataType: "decimal",
      required: false,
      defaultStatus: "optional",
      sectionKey: "moisture_readings",
      displayOrder: 30,
      repeatableGroup: "moisture_readings",
      allowedValues: null,
      unit: "%",
      minimum: 0,
      maximum: 100,
      minLength: null,
      maxLength: null,
      dateRule: null,
      privacyClassification: "operational",
      evidenceRelationship: "none",
      findingRelationship: "none",
      sourceLineageRequired: false,
      correctionGuidance: "Supply the second reading.",
      visibleIf: null,
      requiredIf: null,
    },
  ],
  [
    {
      key: "moisture_readings",
      label: "Moisture readings",
      description: "Repeatable meter readings.",
      displayOrder: 4,
      parentKey: "findings",
      repeatable: true,
    },
  ],
);

const exteriorMapping: SourceMappingProfile = {
  profileKey: "synthetic-exterior-json-v1",
  profileVersion: 1,
  displayName: "Synthetic Exterior Observation JSON mapping",
  synthetic: true,
  sourceType: "json",
  sourceSchemaVersion: "synthetic-exterior-json-1",
  applicableConfiguration: "synthetic-exterior-observation",
  disclosure: DISCLOSURE,
  csvRowMode: "single_record",
  csvScalarStrategy: "not_applicable",
  rules: [
    {
      ruleKey: "client",
      sourcePath: "job.client",
      canonicalField: "client_name",
      transforms: [{ kind: "trim" }, { kind: "collapse_whitespace" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "site",
      sourcePath: "job.site",
      canonicalField: "site_name",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "inspector",
      sourcePath: "inspector.name",
      canonicalField: "inspector_name",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "completed",
      sourcePath: "completed_at",
      canonicalField: "completed_at",
      transforms: [{ kind: "parse_timestamp" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "weather",
      sourcePath: "weather",
      canonicalField: "weather",
      transforms: [{ kind: "trim" }, { kind: "lowercase" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "elevation",
      sourcePath: "elevation",
      canonicalField: "elevation",
      transforms: [{ kind: "trim" }, { kind: "lowercase" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "attestation",
      sourcePath: "attestation",
      canonicalField: "attestation",
      transforms: [{ kind: "boolean_map" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "summary",
      sourcePath: "summary",
      canonicalField: "summary",
      transforms: [{ kind: "trim" }],
      requiredSource: false,
      conflictBehavior: "first_wins",
      nullBehavior: "leave_empty",
    },
  ],
  collections: [
    collection({
      collectionKey: "findings",
      collectionKind: "findings",
      sourcePath: "findings",
      cardinality: "many",
      requiredSource: true,
      emptyBehavior: "allow",
      itemBindings: [
        itemBind("code", "code", true, [{ kind: "trim" }]),
        itemBind("sectionKey", "sectionKey", false, [{ kind: "trim" }]),
        itemBind("title", "title", true, [{ kind: "trim" }]),
        itemBind("description", "description", false, [{ kind: "trim" }]),
        itemBind("severity", "severity", false, [{ kind: "lowercase" }]),
        itemBind("location", "location", false, [{ kind: "trim" }]),
      ],
    }),
    collection({
      collectionKey: "photos",
      collectionKind: "evidence",
      sourcePath: "photos",
      cardinality: "many",
      requiredSource: true,
      emptyBehavior: "allow",
      relationshipBindings: [
        { relationshipKey: "findingCode", sourcePath: "finding", required: false },
      ],
      itemBindings: [
        itemBind("filename", "filename", true, [{ kind: "trim" }]),
        itemBind("contentType", "contentType", false),
        itemBind("sha256", "sha256", true, [{ kind: "trim" }, { kind: "lowercase" }]),
        itemBind("byteLength", "byteLength", false, [{ kind: "parse_integer" }]),
        itemBind("storageRef", "storageRef", false),
        itemBind("caption", "caption", false, [{ kind: "trim" }]),
        itemBind("kind", "kind", false, [{ kind: "lowercase" }]),
        itemBind("findingCode", "finding", false, [{ kind: "trim" }]),
      ],
    }),
    collection({
      collectionKey: "signature",
      collectionKind: "signature",
      sourcePath: "signature",
      cardinality: "one",
      requiredSource: true,
      emptyBehavior: "block",
      itemBindings: [
        itemBind("filename", "filename", false, [{ kind: "trim" }]),
        itemBind("sha256", "sha256", true, [{ kind: "trim" }, { kind: "lowercase" }]),
        itemBind("byteLength", "byteLength", false, [{ kind: "parse_integer" }]),
        itemBind("storageRef", "storageRef", false),
      ],
    }),
  ],
};

const moistureMapping: SourceMappingProfile = {
  profileKey: "synthetic-moisture-csv-v1",
  profileVersion: 1,
  displayName: "Synthetic Moisture Investigation CSV mapping",
  synthetic: true,
  sourceType: "csv",
  sourceSchemaVersion: "synthetic-moisture-csv-1",
  applicableConfiguration: "synthetic-moisture-investigation",
  disclosure: DISCLOSURE,
  csvRowMode: "single_record",
  csvScalarStrategy: "not_applicable",
  rules: [
    {
      ruleKey: "client",
      sourcePath: "client_name",
      canonicalField: "client_name",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "site",
      sourcePath: "site_name",
      canonicalField: "site_name",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "inspector",
      sourcePath: "inspector_name",
      canonicalField: "inspector_name",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "completed",
      sourcePath: "completed_at",
      canonicalField: "completed_at",
      transforms: [{ kind: "parse_timestamp" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "indoor",
      sourcePath: "indoor_rh",
      canonicalField: "indoor_rh",
      transforms: [{ kind: "parse_decimal" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "outdoor",
      sourcePath: "outdoor_rh",
      canonicalField: "outdoor_rh",
      transforms: [{ kind: "parse_decimal" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "r1loc",
      sourcePath: "reading1_location",
      canonicalField: "reading1_location",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "r1pct",
      sourcePath: "reading1_pct",
      canonicalField: "reading1_pct",
      transforms: [{ kind: "parse_decimal" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "r2loc",
      sourcePath: "reading2_location",
      canonicalField: "reading2_location",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "r2pct",
      sourcePath: "reading2_pct",
      canonicalField: "reading2_pct",
      transforms: [{ kind: "parse_decimal" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "finding_code",
      sourcePath: "finding_code",
      canonicalField: "finding_code",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "finding_title",
      sourcePath: "finding_title",
      canonicalField: "finding_title",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "finding_description",
      sourcePath: "finding_description",
      canonicalField: "finding_description",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "photo_filename",
      sourcePath: "photo_filename",
      canonicalField: "photo_filename",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "photo_sha256",
      sourcePath: "photo_sha256",
      canonicalField: "photo_sha256",
      transforms: [{ kind: "trim" }, { kind: "lowercase" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "photo_caption",
      sourcePath: "photo_caption",
      canonicalField: "photo_caption",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "signature",
      sourcePath: "signature_sha256",
      canonicalField: "signature_sha256",
      transforms: [{ kind: "trim" }, { kind: "lowercase" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "attestation",
      sourcePath: "attestation",
      canonicalField: "attestation",
      transforms: [{ kind: "boolean_map" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
  ],
  collections: [
    collection({
      collectionKey: "finding_from_row",
      collectionKind: "findings",
      sourcePath: ".",
      cardinality: "one",
      requiredSource: true,
      emptyBehavior: "block",
      itemBindings: [
        itemBind("code", "finding_code", true, [{ kind: "trim" }]),
        itemBind("title", "finding_title", true, [{ kind: "trim" }]),
        itemBind("description", "finding_description", false, [{ kind: "trim" }]),
        itemBind("sectionKey", "finding_section", false),
        itemBind("severity", "finding_severity", false),
        itemBind("location", "finding_location", false),
      ],
    }),
    collection({
      collectionKey: "photo_from_row",
      collectionKind: "evidence",
      sourcePath: ".",
      cardinality: "one",
      requiredSource: true,
      emptyBehavior: "block",
      relationshipBindings: [
        { relationshipKey: "findingCode", sourcePath: "finding_code", required: false },
      ],
      itemBindings: [
        itemBind("filename", "photo_filename", true, [{ kind: "trim" }]),
        itemBind("sha256", "photo_sha256", true, [{ kind: "trim" }, { kind: "lowercase" }]),
        itemBind("caption", "photo_caption", false, [{ kind: "trim" }]),
        itemBind("findingCode", "finding_code", false, [{ kind: "trim" }]),
      ],
    }),
    collection({
      collectionKey: "signature_from_row",
      collectionKind: "signature",
      sourcePath: ".",
      cardinality: "one",
      requiredSource: true,
      emptyBehavior: "block",
      itemBindings: [
        itemBind("sha256", "signature_sha256", true, [{ kind: "trim" }, { kind: "lowercase" }]),
      ],
    }),
    collection({
      collectionKey: "reading1",
      collectionKind: "repeatable_group",
      sourcePath: ".",
      cardinality: "one",
      destinationGroupKey: "moisture_readings",
      requiredSource: true,
      emptyBehavior: "block",
      itemBindings: [
        itemBind("location", "reading1_location", true, [{ kind: "trim" }]),
        itemBind("percent", "reading1_pct", true, [{ kind: "parse_decimal" }]),
      ],
    }),
    collection({
      collectionKey: "reading2",
      collectionKind: "repeatable_group",
      sourcePath: ".",
      cardinality: "one",
      destinationGroupKey: "moisture_readings",
      requiredSource: true,
      emptyBehavior: "block",
      itemBindings: [
        itemBind("location", "reading2_location", true, [{ kind: "trim" }]),
        itemBind("percent", "reading2_pct", true, [{ kind: "parse_decimal" }]),
      ],
    }),
  ],
};

const exteriorRules: ValidationRuleSet = {
  ruleSetKey: "synthetic-exterior-rules",
  ruleSetVersion: 1,
  displayName: "Synthetic Exterior Observation rules",
  synthetic: true,
  disclosure: DISCLOSURE,
  rules: [
    {
      ruleKey: "client_required",
      label: "Client name required",
      description: "Client name is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "site",
      trigger: { kind: "always" },
      expression: { kind: "required", field: "client_name" },
      remediation: "Enter the client name.",
    },
    {
      ruleKey: "site_required",
      label: "Site name required",
      description: "Site name is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "site",
      trigger: { kind: "always" },
      expression: { kind: "required", field: "site_name" },
      remediation: "Enter the site name.",
    },
    {
      ruleKey: "inspector_required",
      label: "Inspector required",
      description: "Inspector name is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "fieldwork",
      trigger: { kind: "always" },
      expression: { kind: "required", field: "inspector_name" },
      remediation: "Enter the inspector name.",
    },
    {
      ruleKey: "completed_required",
      label: "Completion timestamp required",
      description: "Inspection completed timestamp is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "fieldwork",
      trigger: { kind: "always" },
      expression: { kind: "required", field: "completed_at" },
      remediation: "Enter the completion timestamp.",
    },
    {
      ruleKey: "weather_required",
      label: "Weather required",
      description: "Weather is required for this synthetic exterior profile.",
      severity: "blocking",
      blocking: true,
      sectionKey: "fieldwork",
      trigger: { kind: "always" },
      expression: {
        kind: "allowed_enum",
        field: "weather",
        values: ["clear", "overcast", "rain", "snow"],
      },
      remediation: "Select a weather value from the allowed list.",
    },
    {
      ruleKey: "weather_conditional_elevation",
      label: "Elevation required when weather is recorded",
      description: "Elevation is required when weather is present.",
      severity: "blocking",
      blocking: true,
      sectionKey: "fieldwork",
      trigger: { kind: "field_present", field: "weather" },
      expression: {
        kind: "required_if",
        field: "elevation",
        condition: { kind: "field_present", field: "weather" },
      },
      remediation: "Select the elevation.",
    },
    {
      ruleKey: "min_photo",
      label: "At least one photo",
      description: "At least one photo is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "photos",
      trigger: { kind: "always" },
      expression: { kind: "min_photo_count", minimum: 1 },
      remediation: "Add a photo with a SHA-256 digest.",
    },
    {
      ruleKey: "caption_required",
      label: "Photo captions required",
      description: "Each photo must have a caption.",
      severity: "blocking",
      blocking: true,
      sectionKey: "photos",
      trigger: { kind: "always" },
      expression: { kind: "required_caption" },
      remediation: "Add a caption to every photo.",
    },
    {
      ruleKey: "signature_required",
      label: "Signature required",
      description: "A signature evidence item is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "fieldwork",
      trigger: { kind: "always" },
      expression: { kind: "required_signature" },
      remediation: "Capture inspector signature evidence.",
    },
    {
      ruleKey: "summary_advisory",
      label: "Summary recommended",
      description: "A narrative summary is useful.",
      severity: "advisory",
      blocking: false,
      sectionKey: "findings",
      trigger: { kind: "always" },
      expression: {
        kind: "advisory",
        field: "summary",
        message: "A narrative summary is useful but not required.",
      },
      remediation: "Optionally add a short summary.",
    },
  ],
};

const moistureRules: ValidationRuleSet = {
  ruleSetKey: "synthetic-moisture-rules",
  ruleSetVersion: 1,
  displayName: "Synthetic Moisture Investigation rules",
  synthetic: true,
  disclosure: DISCLOSURE,
  rules: [
    {
      ruleKey: "client_required",
      label: "Client name required",
      description: "Client name is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "site",
      trigger: { kind: "always" },
      expression: { kind: "required", field: "client_name" },
      remediation: "Enter the client name.",
    },
    {
      ruleKey: "site_required",
      label: "Site name required",
      description: "Site name is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "site",
      trigger: { kind: "always" },
      expression: { kind: "required", field: "site_name" },
      remediation: "Enter the site name.",
    },
    {
      ruleKey: "inspector_required",
      label: "Inspector required",
      description: "Inspector name is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "fieldwork",
      trigger: { kind: "always" },
      expression: { kind: "required", field: "inspector_name" },
      remediation: "Enter the inspector name.",
    },
    {
      ruleKey: "indoor_required",
      label: "Indoor RH required",
      description: "Indoor relative humidity is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "fieldwork",
      trigger: { kind: "always" },
      expression: { kind: "required", field: "indoor_rh" },
      remediation: "Enter indoor RH.",
    },
    {
      ruleKey: "rh_range",
      label: "Indoor RH range",
      description: "Indoor RH must be between 0 and 100.",
      severity: "blocking",
      blocking: true,
      sectionKey: "fieldwork",
      trigger: { kind: "always" },
      expression: { kind: "max_number", field: "indoor_rh", maximum: 100 },
      remediation: "Correct the indoor RH reading.",
    },
    {
      ruleKey: "indoor_gt_outdoor_warning",
      label: "Indoor RH higher than outdoor",
      description: "Indoor RH is higher than outdoor RH. This is a warning, not a blocker.",
      severity: "warning",
      blocking: false,
      sectionKey: "fieldwork",
      trigger: { kind: "always" },
      expression: {
        kind: "cross_field_compare",
        leftField: "indoor_rh",
        operator: "lte",
        rightField: "outdoor_rh",
      },
      remediation: "Confirm the humidity readings. This warning does not block report generation.",
    },
    {
      ruleKey: "min_finding",
      label: "Finding required",
      description: "At least one finding is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "findings",
      trigger: { kind: "always" },
      expression: { kind: "min_length", field: "finding_title", minimum: 1 },
      remediation: "Add a finding title.",
    },
    {
      ruleKey: "unique_reading_location",
      label: "Unique reading locations",
      description: "Moisture reading locations must be unique within the group.",
      severity: "warning",
      blocking: false,
      sectionKey: "moisture_readings",
      trigger: { kind: "always" },
      expression: { kind: "unique_in_group", groupKey: "moisture_readings", field: "location" },
      remediation: "Use distinct locations for each reading.",
    },
    {
      ruleKey: "signature_required",
      label: "Signature required",
      description: "A signature evidence item is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "fieldwork",
      trigger: { kind: "always" },
      expression: { kind: "required_signature" },
      remediation: "Capture inspector signature evidence.",
    },
  ],
};

const exteriorTemplate: ReportTemplateDefinition = {
  templateKey: "synthetic-exterior-report",
  templateVersion: 1,
  displayName: "Synthetic Exterior Observation report",
  synthetic: true,
  disclosure: DISCLOSURE,
  applicableSchemaKey: "synthetic-exterior-observation",
  applicableMappingKey: "synthetic-exterior-json-v1",
  rendererAdapter: "bea.deterministic-synthetic-pdf.v1",
  filenamePattern: "BEA-SYN-EXT-{reportRef}-{inspectionRef}.pdf",
  missingValueBehavior: "show_not_recorded",
  headerText: "Synthetic Exterior Observation — not a BEA production template",
  footerText: DISCLOSURE,
  includePageNumbers: true,
  sections: [
    {
      key: "cover",
      title: "Cover",
      displayOrder: 1,
      nodes: [
        { kind: "cover", key: "cover", title: "Synthetic Exterior Observation" },
        { kind: "title", key: "title", text: "Synthetic Exterior Observation Report" },
        { kind: "static_disclaimer", key: "disclaimer", text: DISCLOSURE },
      ],
    },
    {
      key: "site",
      title: "Site",
      displayOrder: 2,
      nodes: [
        { kind: "heading", key: "site-heading", text: "Site" },
        { kind: "label_value", key: "client", fieldKey: "client_name", title: "Client" },
        { kind: "label_value", key: "site", fieldKey: "site_name", title: "Site" },
        { kind: "label_value", key: "weather", fieldKey: "weather", title: "Weather" },
        { kind: "label_value", key: "elevation", fieldKey: "elevation", title: "Elevation" },
      ],
    },
    {
      key: "findings",
      title: "Findings",
      displayOrder: 3,
      nodes: [{ kind: "finding_block", key: "findings" }],
    },
    {
      key: "photos",
      title: "Photo grid",
      displayOrder: 4,
      nodes: [{ kind: "photo_grid", key: "photos", imagePlacement: "grid" }],
    },
    {
      key: "signature",
      title: "Signature",
      displayOrder: 5,
      nodes: [{ kind: "signature_block", key: "signature" }],
    },
  ],
};

const moistureTemplate: ReportTemplateDefinition = {
  templateKey: "synthetic-moisture-report",
  templateVersion: 1,
  displayName: "Synthetic Moisture Investigation report",
  synthetic: true,
  disclosure: DISCLOSURE,
  applicableSchemaKey: "synthetic-moisture-investigation",
  applicableMappingKey: "synthetic-moisture-csv-v1",
  rendererAdapter: "bea.deterministic-synthetic-pdf.v1",
  filenamePattern: "BEA-SYN-MOI-{reportRef}-{inspectionRef}.pdf",
  missingValueBehavior: "show_placeholder",
  headerText: "Synthetic Moisture Investigation — not a BEA production template",
  footerText: DISCLOSURE,
  includePageNumbers: true,
  sections: [
    {
      key: "cover",
      title: "Cover",
      displayOrder: 1,
      nodes: [
        { kind: "cover", key: "cover", title: "Synthetic Moisture Investigation" },
        { kind: "title", key: "title", text: "Synthetic Moisture Investigation Report" },
        { kind: "static_disclaimer", key: "disclaimer", text: DISCLOSURE },
      ],
    },
    {
      key: "conditions",
      title: "Conditions",
      displayOrder: 2,
      nodes: [
        { kind: "heading", key: "conditions-heading", text: "Humidity and readings" },
        { kind: "label_value", key: "client", fieldKey: "client_name", title: "Client" },
        { kind: "label_value", key: "site", fieldKey: "site_name", title: "Site" },
        { kind: "label_value", key: "indoor", fieldKey: "indoor_rh", title: "Indoor RH" },
        { kind: "label_value", key: "outdoor", fieldKey: "outdoor_rh", title: "Outdoor RH" },
        {
          kind: "table",
          key: "readings",
          groupKey: "moisture_readings",
          columns: ["location", "percent"],
          title: "Moisture readings",
        },
      ],
    },
    {
      key: "findings",
      title: "Findings",
      displayOrder: 3,
      nodes: [{ kind: "finding_block", key: "findings" }],
    },
    {
      key: "evidence",
      title: "Evidence list",
      displayOrder: 4,
      nodes: [{ kind: "evidence_block", key: "evidence", imagePlacement: "inline" }],
    },
    {
      key: "signature",
      title: "Signature",
      displayOrder: 5,
      nodes: [{ kind: "signature_block", key: "signature" }],
    },
  ],
};

const storagePolicy = (key: string): StoragePolicyDefinition => ({
  policyKey: key,
  policyVersion: 1,
  synthetic: true,
  disclosure: `${DISCLOSURE} ${BEA_PRODUCTION_POLICY_UNCONFIGURED}`,
  sharePointTenant: null,
  site: null,
  documentLibrary: null,
  projectFolderPattern: "Projects/{projectRef}",
  inspectionFolderPattern: "Projects/{projectRef}/Inspections/{inspectionRef}",
  reportFolderPattern: "Projects/{projectRef}/Inspections/{inspectionRef}/Reports",
  fileNamePattern: "{filename}",
  versionBehavior: "new_version",
  conflictBehavior: "fail",
  metadataFields: ["inspection", "report", "configurationRelease"],
  configured: false,
});

const deliveryPolicy = (key: string): DeliveryPolicyDefinition => ({
  policyKey: key,
  policyVersion: 1,
  synthetic: true,
  disclosure: `${DISCLOSURE} ${BEA_PRODUCTION_POLICY_UNCONFIGURED}`,
  senderMailbox: null,
  toPattern: "client@example.invalid",
  ccPattern: null,
  bccRestricted: true,
  subjectPattern: "Synthetic report {reportRef} for {inspectionRef}",
  bodyTemplate:
    "This is a synthetic dry-run delivery body for {reportRef}. No email is sent. BEA production wording is UNCONFIGURED.",
  attachmentNamePattern: "{filename}",
  deliveryAuthorizerRole: "owner-admin",
  retryPolicy: "manual-retry-after-authorization",
  reconciliationPolicy: "no-live-reconciliation",
  configured: false,
});

const slaPolicy = (key: string): SlaPolicyDefinition => ({
  policyKey: key,
  policyVersion: 1,
  synthetic: true,
  disclosure: `${DISCLOSURE} ${BEA_PRODUCTION_POLICY_UNCONFIGURED}`,
  calendarMode: "calendar_time",
  timeZone: "UTC",
  workdays: [1, 2, 3, 4, 5],
  workdayStartMinute: 8 * 60,
  workdayEndMinute: 17 * 60,
  holidays: [],
  targetMinutes: 24 * 60,
  warningThresholdMinutes: 20 * 60,
  breachThresholdMinutes: 24 * 60,
  pauseReasons: ["customer_caused", "internal_exception", "awaiting_human"],
  attributionCategories: [
    "system_processing",
    "human_waiting",
    "connector_waiting",
    "exception",
    "customer_caused",
  ],
  escalationOwnerRole: "owner-admin",
  configured: false,
});

const workflow: WorkflowBlueprintParameters = {
  policyKey: "inspection-report-workflow",
  policyVersion: 1,
  synthetic: true,
  humanGate: true,
  autoResume: true,
  maxAttempts: 3,
  finalApprovalRequired: true,
};

export const SYNTHETIC_EXTERIOR_JSON_FIXTURE: JsonObject = {
  job: { client: "Northstar Facade Group", site: "Northstar Tower", city: "Chicago" },
  inspector: { name: "Operations Coordinator" },
  completed_at: "2026-08-31T14:30:00.000Z",
  weather: "Clear",
  elevation: "South",
  attestation: true,
  summary: "Synthetic exterior observation package for configuration-lab demonstration.",
  unused_source_note: "This field is intentionally unmapped.",
  findings: [
    {
      code: "EXT-1",
      sectionKey: "envelope",
      title: "Sealant discontinuity",
      description: "Observed sealant gap at the south curtain-wall stack joint.",
      severity: "major",
      location: "South elevation, level 12",
    },
  ],
  photos: [
    {
      filename: "south-joint.jpg",
      sha256: PHOTO_SHA,
      caption: "South joint",
      finding: "EXT-1",
      kind: "photo",
      contentType: "image/jpeg",
      byteLength: 2048,
      storageRef: "synthetic://evidence/south-joint.jpg",
    },
  ],
  signature: {
    filename: "inspector-attestation.sig",
    sha256: SIGNATURE_SHA,
    byteLength: 128,
    storageRef: "synthetic://evidence/inspector-attestation.sig",
  },
};

export const SYNTHETIC_EXTERIOR_CSV_FIXTURE = `client_name,site_name,inspector_name,completed_at,weather,elevation,attestation,finding_code,finding_title,finding_description,photo_filename,photo_sha256,photo_caption,signature_sha256
Northstar Facade Group,Northstar Tower,Operations Coordinator,2026-08-31T14:30:00.000Z,clear,south,true,EXT-1,Sealant discontinuity,Observed sealant gap at the south curtain-wall stack joint.,south-joint.jpg,${PHOTO_SHA},South joint,${SIGNATURE_SHA}
`;

export const SYNTHETIC_MOISTURE_CSV_FIXTURE = `client_name,site_name,inspector_name,completed_at,indoor_rh,outdoor_rh,reading1_location,reading1_pct,reading2_location,reading2_pct,finding_code,finding_title,finding_description,photo_filename,photo_sha256,photo_caption,signature_sha256,attestation
Harborview Property Partners,Harborview Plaza,Operations Coordinator,2026-08-31T14:30:00.000Z,62,48,West wall,18.2,Ceiling cavity,22.4,MOI-1,Elevated moisture,Meter reading indicates elevated moisture at the west wall.,west-wall.jpg,${MOISTURE_PHOTO_SHA},West wall meter,${SIGNATURE_SHA},true
`;

export const SYNTHETIC_MOISTURE_JSON_FIXTURE: JsonObject = {
  client_name: "Harborview Property Partners",
  site_name: "Harborview Plaza",
  inspector_name: "Operations Coordinator",
  completed_at: "2026-08-31T14:30:00.000Z",
  indoor_rh: 62,
  outdoor_rh: 48,
  reading1_location: "West wall",
  reading1_pct: 18.2,
  reading2_location: "Ceiling cavity",
  reading2_pct: 22.4,
  finding_code: "MOI-1",
  finding_title: "Elevated moisture",
  finding_description: "Meter reading indicates elevated moisture at the west wall.",
  photo_filename: "west-wall.jpg",
  photo_sha256: MOISTURE_PHOTO_SHA,
  photo_caption: "West wall meter",
  signature_sha256: SIGNATURE_SHA,
  attestation: true,
  moisture_readings: [
    { location: "West wall", percent: 18.2 },
    { location: "Ceiling cavity", percent: 22.4 },
  ],
};

function pack(
  familyKey: string,
  displayName: string,
  schemaDefinition: InspectionSchemaDefinition,
  mapping: SourceMappingProfile,
  validation: ValidationRuleSet,
  template: ReportTemplateDefinition,
): BoundConfigurationPackage {
  return {
    release: {
      id: familyKey,
      familyKey,
      displayName,
      versionNumber: 1,
      status: "published",
      synthetic: true,
      productionReady: false,
      serviceContextKey: familyKey,
      disclosure: DISCLOSURE,
    },
    schema: schemaDefinition,
    mapping,
    validation,
    template,
    review: { ...defaultReviewPolicy(), policyKey: `${familyKey}-review` },
    storage: storagePolicy(`${familyKey}-storage`),
    delivery: deliveryPolicy(`${familyKey}-delivery`),
    sla: slaPolicy(`${familyKey}-sla`),
    workflow,
  };
}

export const SYNTHETIC_EXTERIOR_PACKAGE = pack(
  "synthetic-exterior-observation",
  "Synthetic Exterior Observation",
  exteriorSchema,
  exteriorMapping,
  exteriorRules,
  exteriorTemplate,
);

export const SYNTHETIC_MOISTURE_PACKAGE = pack(
  "synthetic-moisture-investigation",
  "Synthetic Moisture Investigation",
  moistureSchema,
  moistureMapping,
  moistureRules,
  moistureTemplate,
);

const alternateSchema = schema(
  "synthetic-alternate-collection-lab",
  "Synthetic alternate collection schema",
  [],
  [
    {
      key: "meter_readings",
      label: "Meter readings",
      description: "Repeatable meter readings from a configured collection root.",
      displayOrder: 4,
      parentKey: "findings",
      repeatable: true,
    },
  ],
);

const alternateMapping: SourceMappingProfile = {
  profileKey: "synthetic-alternate-json-v1",
  profileVersion: 1,
  displayName: "Synthetic alternate collection JSON mapping",
  synthetic: true,
  sourceType: "json",
  sourceSchemaVersion: "synthetic-alternate-json-1",
  applicableConfiguration: "synthetic-alternate-collection-lab",
  disclosure: DISCLOSURE,
  csvRowMode: "single_record",
  csvScalarStrategy: "not_applicable",
  rules: [
    {
      ruleKey: "client",
      sourcePath: "inspection.client",
      canonicalField: "client_name",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "site",
      sourcePath: "inspection.site",
      canonicalField: "site_name",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "inspector",
      sourcePath: "inspection.inspector",
      canonicalField: "inspector_name",
      transforms: [{ kind: "trim" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "completed",
      sourcePath: "inspection.completed_at",
      canonicalField: "completed_at",
      transforms: [{ kind: "parse_timestamp" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
    {
      ruleKey: "attestation",
      sourcePath: "inspection.attestation",
      canonicalField: "attestation",
      transforms: [{ kind: "boolean_map" }],
      requiredSource: true,
      conflictBehavior: "reject",
      nullBehavior: "leave_empty",
    },
  ],
  collections: [
    collection({
      collectionKey: "observations_to_findings",
      collectionKind: "findings",
      sourcePath: "inspection.results.observations",
      cardinality: "many",
      requiredSource: true,
      emptyBehavior: "block",
      itemBindings: [
        itemBind("code", "observationId", true, [{ kind: "trim" }]),
        itemBind("title", "heading", true, [{ kind: "trim" }]),
        itemBind("description", "details", false, [{ kind: "trim" }]),
        itemBind("severity", "rating", false, [{ kind: "lowercase" }]),
        itemBind("location", "locationText", false, [{ kind: "trim" }]),
      ],
    }),
    collection({
      collectionKey: "images_to_evidence",
      collectionKind: "evidence",
      sourcePath: "inspection.results.images",
      cardinality: "many",
      requiredSource: true,
      emptyBehavior: "block",
      relationshipBindings: [
        { relationshipKey: "findingCode", sourcePath: "linkedObservation", required: true },
      ],
      itemBindings: [
        itemBind("filename", "file", true, [{ kind: "trim" }]),
        itemBind("sha256", "digest", true, [{ kind: "trim" }, { kind: "lowercase" }]),
        itemBind("caption", "label", false, [{ kind: "trim" }]),
        itemBind("findingCode", "linkedObservation", true, [{ kind: "trim" }]),
      ],
    }),
    collection({
      collectionKey: "signoff_to_signature",
      collectionKind: "signature",
      sourcePath: "inspection.signoff",
      cardinality: "one",
      requiredSource: true,
      emptyBehavior: "block",
      itemBindings: [
        itemBind("filename", "file", false, [{ kind: "trim" }]),
        itemBind("sha256", "digest", true, [{ kind: "trim" }, { kind: "lowercase" }]),
      ],
    }),
    collection({
      collectionKey: "readings_to_group",
      collectionKind: "repeatable_group",
      sourcePath: "inspection.results.readings",
      cardinality: "many",
      destinationGroupKey: "meter_readings",
      requiredSource: true,
      emptyBehavior: "block",
      itemBindings: [
        itemBind("location", "locationName", true, [{ kind: "trim" }]),
        itemBind("percent", "value", true, [{ kind: "parse_decimal" }]),
      ],
    }),
  ],
};

const alternateRules: ValidationRuleSet = {
  ruleSetKey: "synthetic-alternate-rules",
  ruleSetVersion: 1,
  displayName: "Synthetic alternate collection rules",
  synthetic: true,
  disclosure: DISCLOSURE,
  rules: [
    {
      ruleKey: "client_required",
      label: "Client name required",
      description: "Client name is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "site",
      trigger: { kind: "always" },
      expression: { kind: "required", field: "client_name" },
      remediation: "Enter the client name.",
    },
    {
      ruleKey: "signature_required",
      label: "Signature required",
      description: "A signature evidence item is required.",
      severity: "blocking",
      blocking: true,
      sectionKey: "fieldwork",
      trigger: { kind: "always" },
      expression: { kind: "required_signature" },
      remediation: "Capture inspector signature evidence.",
    },
    {
      ruleKey: "unique_reading_location",
      label: "Unique reading locations",
      description: "Meter reading locations must be unique.",
      severity: "warning",
      blocking: false,
      sectionKey: "meter_readings",
      trigger: { kind: "always" },
      expression: { kind: "unique_in_group", groupKey: "meter_readings", field: "location" },
      remediation: "Use distinct locations for each reading.",
    },
  ],
};

const alternateTemplate: ReportTemplateDefinition = {
  templateKey: "synthetic-alternate-report",
  templateVersion: 1,
  displayName: "Synthetic alternate collection report",
  synthetic: true,
  disclosure: DISCLOSURE,
  applicableSchemaKey: "synthetic-alternate-collection-lab",
  applicableMappingKey: "synthetic-alternate-json-v1",
  rendererAdapter: "bea.deterministic-synthetic-pdf.v1",
  filenamePattern: "OFFICIAL-{reportRef}-{inspectionRef}-{projectRef}.pdf",
  missingValueBehavior: "show_not_recorded",
  headerText: "Synthetic alternate collection report — not a BEA production template",
  footerText: DISCLOSURE,
  includePageNumbers: true,
  sections: [
    {
      key: "cover",
      title: "Cover",
      displayOrder: 1,
      nodes: [
        { kind: "cover", key: "cover", title: "Synthetic Alternate Collection" },
        { kind: "title", key: "title", text: "Synthetic Alternate Collection Report" },
        { kind: "static_disclaimer", key: "disclaimer", text: DISCLOSURE },
      ],
    },
    {
      key: "findings",
      title: "Findings",
      displayOrder: 2,
      nodes: [{ kind: "finding_block", key: "findings" }],
    },
    {
      key: "photos",
      title: "Photos",
      displayOrder: 3,
      nodes: [{ kind: "photo_grid", key: "photos", imagePlacement: "grid" }],
    },
    {
      key: "readings",
      title: "Readings",
      displayOrder: 4,
      nodes: [
        {
          kind: "table",
          key: "readings-table",
          groupKey: "meter_readings",
          columns: ["location", "percent"],
          title: "Meter readings",
        },
      ],
    },
    {
      key: "signature",
      title: "Signature",
      displayOrder: 5,
      nodes: [{ kind: "signature_block", key: "signature" }],
    },
  ],
};

export const SYNTHETIC_ALTERNATE_COLLECTION_FIXTURE: JsonObject = {
  inspection: {
    client: "Alternate Facade Lab",
    site: "East Elevation Yard",
    inspector: "Operations Coordinator",
    completed_at: "2026-08-31T14:30:00.000Z",
    attestation: true,
    results: {
      observations: [
        {
          observationId: "OBS-1",
          heading: "Joint opening",
          details: "Opening observed at transition.",
          rating: "major",
          locationText: "East elevation",
        },
        {
          observationId: "OBS-2",
          heading: "Coating damage",
          details: "Localized coating damage.",
          rating: "minor",
          locationText: "North elevation",
        },
      ],
      images: [
        {
          linkedObservation: "OBS-1",
          file: "east-joint.jpg",
          digest: ALT_PHOTO_ONE,
          label: "East joint",
        },
        {
          linkedObservation: "OBS-1",
          file: "east-joint-close.jpg",
          digest: ALT_PHOTO_TWO,
          label: "East joint close-up",
        },
      ],
      readings: [{ locationName: "East wall", value: 18.2 }],
    },
    signoff: {
      file: "signature.sig",
      digest: SIGNATURE_SHA,
    },
  },
};

export const SYNTHETIC_ALTERNATE_COLLECTION_PACKAGE = pack(
  "synthetic-alternate-collection-lab",
  "Synthetic Alternate Collection Lab",
  alternateSchema,
  alternateMapping,
  alternateRules,
  alternateTemplate,
);

export const SYNTHETIC_CONFIGURATION_FAMILIES = [
  SYNTHETIC_EXTERIOR_PACKAGE,
  SYNTHETIC_MOISTURE_PACKAGE,
] as const;

export function syntheticPackageByFamily(familyKey: string): BoundConfigurationPackage | null {
  return (
    SYNTHETIC_CONFIGURATION_FAMILIES.find((item) => item.release.familyKey === familyKey) ?? null
  );
}

const INTAKE_SECTIONS = [
  ["A", "Inspection Inputs"],
  ["B", "Report Structure"],
  ["C", "Validation"],
  ["D", "Review"],
  ["E", "Storage"],
  ["F", "Delivery"],
  ["G", "SLA"],
  ["H", "Sample Package Checklist"],
  ...COMMERCIAL_INTAKE_SECTIONS,
] as const;

const INTAKE_QUESTIONS: readonly {
  readonly key: string;
  readonly section: string;
  readonly prompt: string;
}[] = [
  {
    key: "A.application",
    section: "A",
    prompt: "What application or form produces inspection data?",
  },
  { key: "A.export_formats", section: "A", prompt: "What export formats are available?" },
  { key: "A.field_names", section: "A", prompt: "What are the source field names?" },
  { key: "A.repeating_records", section: "A", prompt: "How are repeating records represented?" },
  { key: "A.photos", section: "A", prompt: "How are photos packaged and identified?" },
  { key: "A.captions", section: "A", prompt: "Where do photo captions live?" },
  { key: "A.signatures", section: "A", prompt: "How are signatures captured?" },
  { key: "A.timestamps", section: "A", prompt: "Which timestamps are authoritative?" },
  { key: "A.inspector_identity", section: "A", prompt: "How is inspector identity represented?" },
  {
    key: "A.source_identifiers",
    section: "A",
    prompt: "What source identifiers must be preserved?",
  },
  { key: "B.editable_source", section: "B", prompt: "What is the editable report source format?" },
  { key: "B.cover_page", section: "B", prompt: "What belongs on the cover page?" },
  { key: "B.sections", section: "B", prompt: "What sections are required, and in what order?" },
  { key: "B.required_wording", section: "B", prompt: "What wording is mandatory versus optional?" },
  { key: "B.findings", section: "B", prompt: "How should findings be presented?" },
  { key: "B.tables", section: "B", prompt: "Which tables are required?" },
  { key: "B.photo_layout", section: "B", prompt: "What photo layout is required?" },
  { key: "B.captions", section: "B", prompt: "How should captions appear on the report?" },
  { key: "B.signatures", section: "B", prompt: "Where do signatures appear?" },
  { key: "B.headers_footers", section: "B", prompt: "What header and footer content is required?" },
  { key: "B.page_numbering", section: "B", prompt: "How should pages be numbered?" },
  { key: "B.disclaimers", section: "B", prompt: "What disclaimers must appear, and where?" },
  { key: "B.file_naming", section: "B", prompt: "What is the delivered file-name pattern?" },
  { key: "C.mandatory_fields", section: "C", prompt: "Which fields are always mandatory?" },
  { key: "C.conditional_fields", section: "C", prompt: "Which fields are conditionally required?" },
  { key: "C.minimum_photos", section: "C", prompt: "What is the minimum photo count?" },
  { key: "C.required_findings", section: "C", prompt: "When is a finding required?" },
  { key: "C.required_signatures", section: "C", prompt: "Which signatures are required?" },
  { key: "C.blocking_vs_warning", section: "C", prompt: "Which rules block versus warn?" },
  { key: "D.technical_reviewer", section: "D", prompt: "Who is the technical reviewer?" },
  { key: "D.correction_owner", section: "D", prompt: "Who owns corrections after review?" },
  { key: "D.self_review", section: "D", prompt: "Is self-review permitted?" },
  { key: "D.final_approval", section: "D", prompt: "What is the final technical approval policy?" },
  { key: "D.delivery_authorization", section: "D", prompt: "Who authorizes client delivery?" },
  {
    key: "E.sharepoint_site",
    section: "E",
    prompt: "What SharePoint site should receive reports?",
  },
  { key: "E.library", section: "E", prompt: "What document library?" },
  { key: "E.folder_hierarchy", section: "E", prompt: "What folder hierarchy?" },
  { key: "E.metadata", section: "E", prompt: "What SharePoint metadata fields?" },
  { key: "E.naming", section: "E", prompt: "What storage naming convention?" },
  { key: "E.versioning", section: "E", prompt: "How should existing files be versioned?" },
  { key: "E.retention", section: "E", prompt: "What retention rules apply?" },
  { key: "F.sending_mailbox", section: "F", prompt: "Which mailbox sends the report?" },
  { key: "F.recipient_source", section: "F", prompt: "Where do To recipients come from?" },
  { key: "F.cc_rules", section: "F", prompt: "What CC rules apply?" },
  { key: "F.subject", section: "F", prompt: "What subject pattern?" },
  { key: "F.body", section: "F", prompt: "What body template?" },
  { key: "F.attachments", section: "F", prompt: "How should attachments be named?" },
  { key: "F.delivery_confirmation", section: "F", prompt: "What counts as delivery confirmation?" },
  { key: "F.retry_failure", section: "F", prompt: "How should retries and failures be handled?" },
  { key: "G.target_turnaround", section: "G", prompt: "What is the target turnaround?" },
  {
    key: "G.business_hours",
    section: "G",
    prompt: "Does SLA use business hours or calendar time?",
  },
  { key: "G.holidays", section: "G", prompt: "Which holidays apply?" },
  { key: "G.pause_conditions", section: "G", prompt: "When may the SLA clock pause?" },
  { key: "G.escalations", section: "G", prompt: "Who owns SLA escalations?" },
  { key: "H.raw_inspection", section: "H", prompt: "Provide a raw inspection package." },
  { key: "H.matching_report", section: "H", prompt: "Provide the matching delivered report." },
  { key: "H.blank_template", section: "H", prompt: "Provide a blank editable template." },
  { key: "H.photos", section: "H", prompt: "Provide the photo set used in that report." },
  { key: "H.reviewer_comments", section: "H", prompt: "Provide sample reviewer comments." },
  { key: "H.delivery_email", section: "H", prompt: "Provide a sample delivery email." },
  {
    key: "H.timestamps",
    section: "H",
    prompt: "Provide approximate timestamps for the sample package.",
  },
  ...COMMERCIAL_INTAKE_QUESTIONS,
];

export function defaultIntakeItems(now: string): ConfigurationIntakeItem[] {
  return INTAKE_QUESTIONS.map((question, index) => ({
    id: `d1000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
    questionKey: question.key,
    sectionKey: question.section,
    prompt: question.prompt,
    status: "awaiting_bea_confirmation",
    answer: null,
    notes: `Synthetic defaults exist for demonstration only. ${BEA_PRODUCTION_POLICY_UNCONFIGURED}`,
    createdAt: now,
    updatedAt: now,
    version: 1,
  }));
}

export const INTAKE_SECTION_LABELS: Readonly<Record<string, string>> = Object.fromEntries(
  INTAKE_SECTIONS.map(([key, label]) => [key, label]),
);

export function defaultReadinessItems(now: string): ConfigurationReadinessItem[] {
  const items: Array<
    Omit<ConfigurationReadinessItem, "id" | "createdAt" | "updatedAt" | "version">
  > = [
    {
      gapKey: "source-application",
      area: "Inspection Inputs",
      description: "BEA inspection source application and export format are unknown.",
      currentSyntheticBehavior: "JSON and CSV synthetic fixtures exercise the mapping engine.",
      whyConfirmationRequired: "Production mapping cannot be authored without the real export.",
      blockingStage: "production_mapping",
      responsiblePerson: "Owner",
      targetMeeting: "Thursday, 3 September 2026",
      status: "awaiting_bea_confirmation",
      resolution: null,
      configurationArtifactKind: "mapping_profile",
    },
    {
      gapKey: "report-template",
      area: "Report Structure",
      description: "Editable BEA report template is not available.",
      currentSyntheticBehavior: "Two synthetic templates render through the same document model.",
      whyConfirmationRequired: "Production layout, wording, and photo rules must come from BEA.",
      blockingStage: "production_template",
      responsiblePerson: "Owner",
      targetMeeting: "Thursday, 3 September 2026",
      status: "awaiting_bea_confirmation",
      resolution: null,
      configurationArtifactKind: "report_template",
    },
    {
      gapKey: "validation-policy",
      area: "Validation",
      description: "Mandatory fields, photo minima, and blocking rules are unconfirmed.",
      currentSyntheticBehavior: "Synthetic blocking and warning rules demonstrate the engine.",
      whyConfirmationRequired: "Treating demo rules as BEA policy would bury unknowns in code.",
      blockingStage: "production_activation",
      responsiblePerson: "Owner",
      targetMeeting: "Thursday, 3 September 2026",
      status: "awaiting_bea_confirmation",
      resolution: null,
      configurationArtifactKind: "validation_rule_set",
    },
    {
      gapKey: "review-policy",
      area: "Review",
      description: "BEA reviewer assignment and self-review policy are unconfirmed.",
      currentSyntheticBehavior:
        "Safe defaults: one technical approval, no self-review, Owner delivery authorization.",
      whyConfirmationRequired:
        "Reviewer identity and self-review must be confirmed before production activation.",
      blockingStage: "production_activation",
      responsiblePerson: "Owner",
      targetMeeting: "Thursday, 3 September 2026",
      status: "awaiting_bea_confirmation",
      resolution: null,
      configurationArtifactKind: "review_policy",
    },
    {
      gapKey: "sharepoint-storage",
      area: "Storage",
      description: "SharePoint site, library, folders, and metadata are unknown.",
      currentSyntheticBehavior:
        "Dry-run folder and file names are placeholders. No Graph call is made.",
      whyConfirmationRequired: "Live storage cannot be activated without destination confirmation.",
      blockingStage: "connector_activation",
      responsiblePerson: "Owner",
      targetMeeting: "Thursday, 3 September 2026",
      status: "awaiting_bea_confirmation",
      resolution: null,
      configurationArtifactKind: "storage_policy",
    },
    {
      gapKey: "outlook-delivery",
      area: "Delivery",
      description: "Sending mailbox, recipients, subject, and body are unknown.",
      currentSyntheticBehavior:
        "Local-test delivery to client@example.invalid. Live Outlook remains not connected.",
      whyConfirmationRequired:
        "No client email may be sent until mailbox and recipients are confirmed.",
      blockingStage: "connector_activation",
      responsiblePerson: "Owner",
      targetMeeting: "Thursday, 3 September 2026",
      status: "awaiting_bea_confirmation",
      resolution: null,
      configurationArtifactKind: "delivery_policy",
    },
    {
      gapKey: "sla-calendar",
      area: "SLA",
      description: "BEA SLA calendar, holidays, and pause policy are unconfirmed.",
      currentSyntheticBehavior:
        "Calendar-time 24-hour placeholder. Business-hours mode exists but is not BEA policy.",
      whyConfirmationRequired: "A synthetic calendar must not be presented as BEA policy.",
      blockingStage: "production_activation",
      responsiblePerson: "Owner",
      targetMeeting: "Thursday, 3 September 2026",
      status: "awaiting_bea_confirmation",
      resolution: null,
      configurationArtifactKind: "sla_policy",
    },
    {
      gapKey: "sample-package",
      area: "Sample Package Checklist",
      description:
        "Raw inspection, matching report, blank template, photos, comments, and email are not yet provided.",
      currentSyntheticBehavior:
        "Synthetic lab packages prove the framework without client production data.",
      whyConfirmationRequired: "Thursday mapping requires the real sample set.",
      blockingStage: "thursday_mapping",
      responsiblePerson: "Owner",
      targetMeeting: "Thursday, 3 September 2026",
      status: "awaiting_bea_confirmation",
      resolution: null,
      configurationArtifactKind: null,
    },
    ...COMMERCIAL_READINESS_GAPS.map((gap) => ({
      gapKey: gap.gapKey,
      area: gap.area,
      description: gap.description,
      currentSyntheticBehavior:
        "Synthetic catalogs, prices, and proposal templates exist for laboratory demonstration only.",
      whyConfirmationRequired:
        "Owner's Thursday commercial materials are required before production.",
      blockingStage: "production_activation",
      responsiblePerson: "Owner",
      targetMeeting: "Thursday, 3 September 2026",
      status: "awaiting_bea_confirmation" as const,
      resolution: null,
      configurationArtifactKind: null,
    })),
  ];
  return items.map((item, index) => ({
    ...item,
    id: `d2000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`,
    createdAt: now,
    updatedAt: now,
    version: 1,
  }));
}

export function exportIntakePacketMarkdown(
  items: readonly ConfigurationIntakeItem[],
  gaps: readonly ConfigurationReadinessItem[],
): string {
  const lines = [
    "# BEA configuration intake packet",
    "",
    "Status values are not confirmed merely because a synthetic default exists.",
    "",
    `Generated for the Thursday, 3 September 2026 owner meeting.`,
    "",
  ];
  for (const [key, label] of INTAKE_SECTIONS) {
    lines.push(`## ${key}. ${label}`, "");
    for (const item of items.filter((entry) => entry.sectionKey === key)) {
      lines.push(`- **${item.questionKey}** (${item.status}): ${item.prompt}`);
      lines.push(`  - Answer: ${item.answer ?? "(none)"}`);
      if (item.notes) lines.push(`  - Notes: ${item.notes}`);
    }
    lines.push("");
  }
  lines.push("## Data-gap registry", "");
  for (const gap of gaps) {
    lines.push(`- **${gap.gapKey}** [${gap.status}] ${gap.description}`);
    lines.push(`  - Blocking stage: ${gap.blockingStage}`);
    lines.push(`  - Synthetic behavior: ${gap.currentSyntheticBehavior}`);
  }
  return `${lines.join("\n")}\n`;
}

export function exportIntakePacketJson(
  items: readonly ConfigurationIntakeItem[],
  gaps: readonly ConfigurationReadinessItem[],
): JsonObject {
  return {
    meeting: "Thursday, 3 September 2026",
    disclosure: BEA_PRODUCTION_POLICY_UNCONFIGURED,
    intake: items.map((item) => ({
      questionKey: item.questionKey,
      sectionKey: item.sectionKey,
      prompt: item.prompt,
      status: item.status,
      answer: item.answer,
      notes: item.notes,
    })),
    gaps: gaps.map((gap) => ({
      gapKey: gap.gapKey,
      area: gap.area,
      status: gap.status,
      blockingStage: gap.blockingStage,
      description: gap.description,
    })),
  };
}
